[build]
  cmd = "go build -o ./tmp/fat-morph ."
  bin = "./tmp/fat-morph"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  send_interrupt = true
  kill_delay = 1000

[log]
  time = true

[misc]
  clean_on_exit = true
